version: "3.7"
services:
  postgres:
    # build: .
    image: postgres:14.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    expose:
      - "5432"
    ports:
      - 3006:5432
    volumes:
      # - ./mount:/var/lib/postgresql/data
      - ./db_sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    image: tomcat:9.0.55-jdk17-corretto
    restart: always
    network_mode: host
    expose:
      - "8080"
    ports:
      - 8081:8080
    
    volumes:
      - ./webapp:/usr/local/tomcat/webapps/hotel
